# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCozxSHBbO7-IpqRAhVHPcRGIHqYdoUx
"""

# Basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
import random

# ML / DL
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.cluster import MiniBatchKMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import (
    calinski_harabasz_score,
    davies_bouldin_score,
    silhouette_score,
    adjusted_rand_score
)

import tensorflow as tf
from tensorflow.keras import layers, models
import umap

"""Ερώτημα 1 & 2"""

# Load Fashion-MNIST
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

# Normalize to [0,1]
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# Flatten images
x_train = x_train.reshape(len(x_train), -1)
x_test = x_test.reshape(len(x_test), -1)

# Train / Validation split
x_train, x_val, y_train, y_val = train_test_split(
    x_train, y_train, test_size=0.2, random_state=42
)

print("Train:", x_train.shape)
print("Validation:", x_val.shape)
print("Test:", x_test.shape)

"""Ερώτημα 4 – raw images"""

def plot_random_images(images, labels, title):
    plt.figure(figsize=(10,3))
    classes = np.unique(labels)
    for i, cls in enumerate(classes[:10]):
        idx = np.random.choice(np.where(labels == cls)[0])
        plt.subplot(1,10,i+1)
        plt.imshow(images[idx].reshape(28,28), cmap="gray")
        plt.title(str(cls))
        plt.axis("off")
    plt.suptitle(title)
    plt.show()

plot_random_images(x_train, y_train, "Random Fashion-MNIST Images (Raw)")

"""Ερώτημα 3 + 5"""

start = time.time()
pca = PCA(n_components=64)
x_train_pca = pca.fit_transform(x_train)
pca_time = time.time() - start

# Scree plot
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.title("PCA Scree Plot")
plt.show()

"""Ερώτημα 3 + παρατηρήσεις α,β,γ"""

input_dim = x_train.shape[1]
encoding_dim = 64

input_layer = layers.Input(shape=(input_dim,))
encoded = layers.Dense(256, activation="relu")(input_layer)
encoded = layers.Dense(128, activation="relu")(encoded)
encoded = layers.Dense(encoding_dim, activation="relu")(encoded)

decoded = layers.Dense(128, activation="relu")(encoded)
decoded = layers.Dense(256, activation="relu")(decoded)
decoded = layers.Dense(input_dim, activation="sigmoid")(decoded)

autoencoder = models.Model(input_layer, decoded)
encoder = models.Model(input_layer, encoded)

autoencoder.compile(optimizer="adam", loss="mse")

start = time.time()
autoencoder.fit(
    x_train, x_train,
    epochs=20,
    batch_size=256,
    validation_data=(x_val, x_val),
    verbose=1
)
sae_time = time.time() - start

"""SAE Reconstructions

(Ερώτημα 4)
"""

reconstructed = autoencoder.predict(x_test[:10])

plt.figure(figsize=(10,3))
for i in range(10):
    plt.subplot(2,10,i+1)
    plt.imshow(x_test[i].reshape(28,28), cmap="gray")
    plt.axis("off")

    plt.subplot(2,10,i+11)
    plt.imshow(reconstructed[i].reshape(28,28), cmap="gray")
    plt.axis("off")

plt.suptitle("Original (top) vs Reconstructed (bottom)")
plt.show()

"""UMAP

(3η τεχνική DR)
"""

start = time.time()
umap_model = umap.UMAP(n_components=64, random_state=42)
x_train_umap = umap_model.fit_transform(x_train)
umap_time = time.time() - start

"""Encode Test Data

(Ερώτημα 6)
"""

x_test_pca = pca.transform(x_test)
x_test_sae = encoder.predict(x_test)
x_test_umap = umap_model.transform(x_test)

"""Clustering & Metrics

(Ερωτήματα 7, 8, 9)
"""

def evaluate(X, labels, y_true):
    #For DBSCAN, clusters are estimated excluding noise points (-1)
    mask = labels != -1
    return (
        calinski_harabasz_score(X[mask], labels[mask]),
        davies_bouldin_score(X[mask], labels[mask]),
        silhouette_score(X[mask], labels[mask]),
        adjusted_rand_score(y_true[mask], labels[mask])
    )

results = []

def run_clustering(X, y, dr_name, dr_time):
    algorithms = {
        "MiniBatchKMeans": MiniBatchKMeans(n_clusters=10),
        "DBSCAN": DBSCAN(eps=3),
        "Agglomerative": AgglomerativeClustering(n_clusters=10)
    }

    for name, algo in algorithms.items():
        start = time.time()
        labels = algo.fit_predict(X)
        cluster_time = time.time() - start

        ch, db, sil, ari = evaluate(X, labels, y)

        results.append([
            dr_name, name, dr_time, cluster_time,
            len(set(labels)) - (1 if -1 in labels else 0),
            ch, db, sil, ari
        ])

"""Run All Experiments"""

run_clustering(x_test, y_test, "Raw", 0)
run_clustering(x_test_pca, y_test, "PCA", pca_time)
run_clustering(x_test_sae, y_test, "SAE", sae_time)
run_clustering(x_test_umap, y_test, "UMAP", umap_time)

"""Results DataFrame

(Ερώτημα 9)
"""

columns = [
    "Dimensionality Reduction",
    "Clustering Algorithm",
    "DR Time (s)",
    "Clustering Time (s)",
    "Clusters",
    "Calinski-Harabasz",
    "Davies-Bouldin",
    "Silhouette",
    "ARI"
]

df = pd.DataFrame(results, columns=columns)
df

"""For easier comparison between dimensionality reduction and clustering combinations, a summary of the evaluation metrics was produced."""

# Summary comparison (for report support)

summary_df = (
    df
    .groupby(["Dimensionality Reduction", "Clustering Algorithm"])
    [["Silhouette", "ARI"]]
    .mean()
    .round(3)
)

summary_df

"""Cluster Visualization

(Ερώτημα 10)
"""

chosen_classes = [0, 1, 2, 3]

kmeans = MiniBatchKMeans(n_clusters=10, random_state=42)
labels = kmeans.fit_predict(x_test_pca)

for cls in chosen_classes:
    idx = np.random.choice(
        np.where(y_test == cls)[0],
        size=5,
        replace=False
    )

    plt.figure(figsize=(6,2))
    for i, id_ in enumerate(idx):
        plt.subplot(1,5,i+1)
        plt.imshow(x_test[id_].reshape(28,28), cmap="gray")
        plt.title(f"C{labels[id_]}")
        plt.axis("off")

    plt.suptitle(f"Class {cls} – PCA + KMeans (Cluster IDs)")
    plt.show()